"""add revised exams

Revision ID: 1b44bdde6c5a
Revises: ced4774d0f97
Create Date: 2021-12-08 16:56:14.752456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b44bdde6c5a'
down_revision = 'ced4774d0f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revised_exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submitted_exam_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('reviewer_role', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_exam_id'], ['submitted_exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revised_exams')
    # ### end Alembic commands ###
