"""add tags and media to courses

Revision ID: 3950015b19bf
Revises: d4d704640d37
Create Date: 2021-11-08 00:34:14.713106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3950015b19bf'
down_revision = 'd4d704640d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('creator', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('location', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('tags', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('courses', sa.Column('media', sa.ARRAY(sa.String()), nullable=False))
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('courses', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('courses', 'media')
    op.drop_column('courses', 'tags')
    op.drop_column('courses', 'location')
    op.drop_column('courses', 'creator')
    # ### end Alembic commands ###
