"""Add Exams to Courses

Revision ID: 3a66dc1e56cc
Revises: 065e36bedcd5
Create Date: 2021-10-23 04:51:55.962793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a66dc1e56cc'
down_revision = '065e36bedcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('exams', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'exams')
    # ### end Alembic commands ###
