"""exam comments for revised exams

Revision ID: 3f7117d9c622
Revises: 9df5413db4e3
Create Date: 2021-12-12 17:53:19.094732

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '3f7117d9c622'
down_revision = '9df5413db4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('revised_exams', 'exams_reviews')

    op.alter_column(table_name='exams_reviews', column_name='reviewer_role', new_column_name='feedback', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='exams_reviews', column_name='feedback', new_column_name='reviewer_role')

    op.rename_table('exams_reviews', 'revised_exams')
    # ### end Alembic commands ###
