"""exams add published column

Revision ID: 9df5413db4e3
Revises: 1b44bdde6c5a
Create Date: 2021-12-10 23:24:34.794145

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9df5413db4e3'
down_revision = '1b44bdde6c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('published', sa.Boolean(), nullable=True))
    op.execute("UPDATE exams SET published = true")
    op.alter_column('exams', 'published', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'published')
    # ### end Alembic commands ###
