"""Add Subscription to Courses

Revision ID: bcf0b2ae7a3a
Revises: 3a66dc1e56cc
Create Date: 2021-10-23 16:44:08.317080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf0b2ae7a3a'
down_revision = '3a66dc1e56cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('subscription', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'subscription')
    # ### end Alembic commands ###
