"""add submitted exams by students

Revision ID: ced4774d0f97
Revises: 4c00b59a46d6
Create Date: 2021-12-07 01:29:51.501955

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ced4774d0f97'
down_revision = '26751a8282ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_exams',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('student_id', sa.String(), nullable=True),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.Column('exam_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
                    sa.ForeignKeyConstraint(['student_id', 'course_id'], ['students.id', 'students.course_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('answers',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('submitted_exam_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
                    sa.ForeignKeyConstraint(['submitted_exam_id'], ['submitted_exams.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('submitted_exams')
    # ### end Alembic commands ###
