"""add types to courses

Revision ID: d4d704640d37
Revises: bcf0b2ae7a3a
Create Date: 2021-11-06 04:44:24.741409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d704640d37'
down_revision = 'bcf0b2ae7a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'type')
    # ### end Alembic commands ###
