"""add enrollment date to students

Revision ID: de55850a8987
Revises: 3f7117d9c622
Create Date: 2021-12-19 17:40:23.720281

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'de55850a8987'
down_revision = '3f7117d9c622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='students', column_name='id', new_column_name='student_id')
    op.add_column('students', sa.Column('enrollment_datetime', sa.DateTime(), nullable=False,
                                        server_default=sa.func.current_timestamp()))

    op.drop_constraint('submitted_exams_student_id_course_id_fkey', 'submitted_exams', type_='foreignkey')
    op.create_foreign_key(None, 'submitted_exams', 'students', ['student_id', 'course_id'], ['student_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='students', column_name='student_id', new_column_name='id')

    op.drop_constraint(None, 'submitted_exams', type_='foreignkey')
    op.create_foreign_key('submitted_exams_student_id_course_id_fkey', 'submitted_exams', 'students',
                          ['student_id', 'course_id'], ['id', 'course_id'])

    op.drop_column('students', 'enrollment_datetime')
    # ### end Alembic commands ###
