name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COV_OUTFILE: coverage.xml
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Unit & Integration test
        run: |
          pip install pytest
          pip install pytest-cov
          coverage run -m pytest tests/
          coverage run -a -m behave
          coverage report -m
          coverage html
